@param app.Page page

<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chocolademelktijd?</title>
    <link rel="stylesheet" href="css/yyy.css">
</head>

<body>
    <div id="content">
        <h1>Is het al chocolademelktijd?</h1>
        <div class="output_positive">${page.chocoladeMelkTijd}</div>
        <script>./javascript/index.js</script>
    </div>
</body>
</html>